const createTypeRole = (
  weight: number,
  size: string,
  lineHeight: number,
  family: string,
) => `${weight} ${size}/${lineHeight} ${family}`;

export const mongoliaTheme = {
  color: {
    bg: "#090304",
    bgTop: "#2a070a",
    bgDeep: "#050102",
    foreground: "#fff7ed",
    foregroundSoft: "#f0dcc2",
    muted: "#be9f86",
    primary: "#d8221b",
    primarySoft: "rgba(216, 34, 27, 0.18)",
    primaryStrong: "#ff5442",
    secondary: "#f3c14d",
    surface: "rgba(21, 9, 11, 0.78)",
    surfaceStrong: "rgba(28, 11, 13, 0.94)",
    surfaceAccent: "rgba(74, 17, 13, 0.82)",
    surfaceMedia: "rgba(42, 15, 11, 0.86)",
    borderSoft: "rgba(243, 193, 77, 0.14)",
    borderStrong: "rgba(255, 214, 112, 0.34)",
    gridLine: "rgba(255, 222, 163, 0.06)",
    glow: "rgba(255, 195, 79, 0.3)",
  },
  chrome: {
    headerSurface: "rgba(13, 7, 8, 0.78)",
    headerBorder: "rgba(255, 214, 112, 0.26)",
    headerShadow: "0 24px 80px rgba(0, 0, 0, 0.38)",
    footerSurface: "rgba(14, 8, 9, 0.9)",
    footerBorder: "rgba(255, 214, 112, 0.16)",
  },
  component: {
    cardSurface: "rgba(20, 9, 10, 0.84)",
    cardSurfaceStrong: "rgba(29, 11, 12, 0.96)",
    cardBorder: "rgba(255, 214, 112, 0.14)",
    mediaSurface: "linear-gradient(135deg, rgba(88, 19, 14, 0.9), rgba(24, 8, 12, 0.95))",
    buttonBg: "linear-gradient(135deg, #f3c14d, #ffda6c)",
    buttonFg: "#1b0d08",
    buttonBorder: "rgba(255, 241, 206, 0.28)",
  },
  radius: {
    sm: "0.8rem",
    md: "1.1rem",
    lg: "1.5rem",
    xl: "2rem",
    pill: "999px",
  },
  shadow: {
    soft: "0 18px 60px rgba(0, 0, 0, 0.22)",
    card: "0 24px 70px rgba(0, 0, 0, 0.26)",
    hero: "0 34px 100px rgba(0, 0, 0, 0.34)",
    glow: "0 0 0 1px rgba(255, 219, 147, 0.06), 0 26px 70px rgba(255, 176, 62, 0.12)",
  },
  motion: {
    fast: "220ms",
    base: "420ms",
    slow: "760ms",
    loop: "5200ms",
  },
  type: {
    display: createTypeRole(
      700,
      "clamp(3.2rem, 7vw, 5.6rem)",
      0.94,
      "var(--font-display)",
    ),
    heading: createTypeRole(
      650,
      "clamp(2rem, 4vw, 3.35rem)",
      1.02,
      "var(--font-display)",
    ),
    subheading: createTypeRole(
      500,
      "clamp(1.05rem, 2.1vw, 1.28rem)",
      1.65,
      "var(--font-body)",
    ),
    cardTitle: createTypeRole(
      600,
      "clamp(1.1rem, 2vw, 1.42rem)",
      1.2,
      "var(--font-display)",
    ),
    bodyLg: createTypeRole(
      500,
      "clamp(1.05rem, 1.8vw, 1.22rem)",
      1.72,
      "var(--font-body)",
    ),
    body: createTypeRole(400, "1rem", 1.7, "var(--font-body)"),
    label: createTypeRole(600, "0.78rem", 1.1, "var(--font-body)"),
    meta: createTypeRole(500, "0.82rem", 1.3, "var(--font-body)"),
    metric: createTypeRole(
      700,
      "clamp(1.3rem, 3.1vw, 2.2rem)",
      1,
      "var(--font-display)",
    ),
  },
} as const;

export const mongoliaThemeCssVariables = {
  "--color-bg": mongoliaTheme.color.bg,
  "--color-bg-top": mongoliaTheme.color.bgTop,
  "--color-bg-deep": mongoliaTheme.color.bgDeep,
  "--color-foreground": mongoliaTheme.color.foreground,
  "--color-foreground-soft": mongoliaTheme.color.foregroundSoft,
  "--color-muted": mongoliaTheme.color.muted,
  "--color-primary": mongoliaTheme.color.primary,
  "--color-primary-soft": mongoliaTheme.color.primarySoft,
  "--color-primary-strong": mongoliaTheme.color.primaryStrong,
  "--color-secondary": mongoliaTheme.color.secondary,
  "--color-surface": mongoliaTheme.color.surface,
  "--color-surface-strong": mongoliaTheme.color.surfaceStrong,
  "--color-surface-accent": mongoliaTheme.color.surfaceAccent,
  "--color-surface-media": mongoliaTheme.color.surfaceMedia,
  "--color-border-soft": mongoliaTheme.color.borderSoft,
  "--color-border-strong": mongoliaTheme.color.borderStrong,
  "--color-grid-line": mongoliaTheme.color.gridLine,
  "--color-glow": mongoliaTheme.color.glow,
  "--header-surface": mongoliaTheme.chrome.headerSurface,
  "--header-border": mongoliaTheme.chrome.headerBorder,
  "--header-shadow": mongoliaTheme.chrome.headerShadow,
  "--footer-surface": mongoliaTheme.chrome.footerSurface,
  "--footer-border": mongoliaTheme.chrome.footerBorder,
  "--card-surface": mongoliaTheme.component.cardSurface,
  "--card-surface-strong": mongoliaTheme.component.cardSurfaceStrong,
  "--card-border": mongoliaTheme.component.cardBorder,
  "--media-surface": mongoliaTheme.component.mediaSurface,
  "--button-bg": mongoliaTheme.component.buttonBg,
  "--button-fg": mongoliaTheme.component.buttonFg,
  "--button-border": mongoliaTheme.component.buttonBorder,
  "--radius-sm": mongoliaTheme.radius.sm,
  "--radius-md": mongoliaTheme.radius.md,
  "--radius-lg": mongoliaTheme.radius.lg,
  "--radius-xl": mongoliaTheme.radius.xl,
  "--radius-pill": mongoliaTheme.radius.pill,
  "--shadow-soft": mongoliaTheme.shadow.soft,
  "--shadow-card": mongoliaTheme.shadow.card,
  "--shadow-hero": mongoliaTheme.shadow.hero,
  "--shadow-glow": mongoliaTheme.shadow.glow,
  "--motion-fast": mongoliaTheme.motion.fast,
  "--motion-base": mongoliaTheme.motion.base,
  "--motion-slow": mongoliaTheme.motion.slow,
  "--motion-loop": mongoliaTheme.motion.loop,
  "--type-display": mongoliaTheme.type.display,
  "--type-heading": mongoliaTheme.type.heading,
  "--type-subheading": mongoliaTheme.type.subheading,
  "--type-card-title": mongoliaTheme.type.cardTitle,
  "--type-body-lg": mongoliaTheme.type.bodyLg,
  "--type-body": mongoliaTheme.type.body,
  "--type-label": mongoliaTheme.type.label,
  "--type-meta": mongoliaTheme.type.meta,
  "--type-metric": mongoliaTheme.type.metric,
} as const;
